---
- name: Placing configuration files for cluster
  hosts: hadoop
  gather_facts: false
  tasks:
  - name: Hadoop conf
    synchronize:
      src:  './cf15-hadoop/{{ item }}'
      dest: '~hadoopuser/HA/hadoop/etc/hadoop/{{ item }}'
    with_items:
      - core-site.xml
      - hdfs-site.xml
      - mapred-site.xml
      - yarn-site.xml
      - slaves
  - name: HBase conf
    synchronize:
      src:  './cf15-hbase/{{ item }}'
      dest: '~hadoopuser/HA/hbase/conf/{{ item }}'
    with_items:
      - hbase-site.xml
      - regionservers
  - name: ZooKeeper conf
    synchronize:
      src:  './cf15-zk/{{ item }}'
      dest: '~hadoopuser/HA/zookeeper/conf/{{ item }}'
    with_items:
      - zoo.cfg
