---
- name: Downloading and unpacking HADOOP
  hosts: hadoop
  gather_facts: false
  tasks:
  - name: Create HA directory
    file:
      path: ~hadoopuser/HA
      state: directory
  - name: Unpacking Hadoop
    unarchive:
      src: '~/hadoop_distfiles/{{ item.name }}.tar.gz'
      dest: ~hadoopuser/HA
      owner: hadoopuser
      group: hadoopuser
      creates: ~hadoopuser/HA/{{ item.target }}
    with_items:
      - {name: 'hadoop-2.5.2', target: 'hadoop'}
      - {name: 'hbase-1.2.3-bin', target: 'hbase'}
      - {name: 'zookeeper-3.4.9', target: 'zookeeper'}
  - name: Rename dir
    command: 'mv ~hadoopuser/HA/{{ item.name }} ~hadoopuser/HA/{{ item.target }}'
    args:
      creates: ~hadoopuser/HA/{{ item.target }}
    with_items:
      - {name: 'hadoop-2.5.2', target: 'hadoop'}
      - {name: 'hbase-1.2.3', target: 'hbase'}
      - {name: 'zookeeper-3.4.9', target: 'zookeeper'}
  - name: Clean downloaded
    file:
      path: '~hadoopuser/{{ item.name }}.tar.gz'
      state: absent
    with_items:
      - {name: 'hadoop-2.5.2', target: 'hadoop'}
      - {name: 'hbase-1.2.3-bin', target: 'hbase'}
      - {name: 'zookeeper-3.4.9', target: 'zookeeper'}