---
- name: Installing prerequisites for HADOOP
  hosts: hadoop
  become: true
  gather_facts: false
  tasks:
  - name: Installing Java
    yum:
      name: java-1.8.0
      state: latest
  - name: Installing Midnight Commander
    yum:
      name: mc
      state: latest
  - name: Create --hadoopuser--
    user:
      name: hadoopuser
      shell: '/usr/bin/bash'
      password: $1$abC$bnHkUrTarL4ffXu4Hu9Y1.
      create_home: yes